### ISSUE TITLE
limits key not fully functional

### ISSUE THREAD

**Issue by kkebb** [signalfuse/maestro-ng#137]
Hello,

Firstly, thank you for integrating the limits option to the maestro-ng package!

However, I was playing around with the setting for one of my services as follows:
```
test:
    image: busybox
    instances:
      bb1:
        ship: boot2docker
        limits:
          memory: 512m
          cpu: 1
        command: /bin/sh -c "while true; do echo hello world; sleep 1; done"
```
and when I ran a docker stats, this is what I see as a result:
```
docker stats $(docker inspect --format='{{.Name}}' $(docker ps -aq --no-trunc))
```
```
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
/bb1                0.11%               536.6 kB/8.165 GB   0.01%               0 B/0 B
```
and based off the limit of 512m that I had set in the YAML file, it is not being reflected when I run the docker stats.

Thank you very much in advance, really appreciate it!
