### ISSUE TITLE
Data container state not being reflected appropriately

### ISSUE THREAD

**Issue by kkebb** [signalfuse/maestro-ng#139]
Hello again!

Your tool is amazing, and am loving it's seamless integration with the docker commands. It just came to my attention that it seems that when we define data containers in the YAML file and run a status check against the container, we see that the container is marked as "down for <time>" in red, instead of the status being marked as N/A, or a more appropriate label for the status of a data container.
Example:
```
data:
    image: busybox
    instances:
      data1:
        ship: boot2docker
        container_volumes:
          - /path/to/dir
```
RESULT:
```
  #  INSTANCE                                 SERVICE              SHIP                                     CONTAINER                  STATUS    
  1. data1                                    data                 boot2docker                              latest:51106c7             down for 5s
```
