### ISSUE TITLE
Ability to define lifecycle checks at the service level

### ISSUE THREAD

**Issue by iangkent** [signalfuse/maestro-ng#156]
Currently maestro only supports lifecycle checks defined in service instance level.
http://maestro-ng.readthedocs.org/en/latest/#lifecycle-checks

However, when the lifecycle check is the same for each instance of the service it would be nice to define the check at service level. We did refactor the checks to service level and did not receive error when maestro parsed the yaml. It tool us a while to notice that only the default checks were happening.

```yaml
  zookeeper:
    image: docker.cenx.localnet:5000/zookeeper
    lifecycle:
      running: [{type: tcp, port: client}]
    instances:
      zk1:
        ship: ship1
        ports: {client: 2181, peer: 2888, election: 3888, jmx: 9000}
      zk2:
        ship: ship2
        ports: {client: 2181, peer: 2888, election: 3888, jmx: 9000}
      zk3:
        ship: ship3
        ports: {client: 2181, peer: 2888, election: 3888, jmx: 9000}
```
versus
```yaml
  zookeeper:
    image: docker.cenx.localnet:5000/zookeeper
    instances:
      zk1:
        ship: ship1
        ports: {client: 2181, peer: 2888, election: 3888, jmx: 9000}
        lifecycle:
          running: [{type: tcp, port: client}]
      zk2:
        ship: ship2
        ports: {client: 2181, peer: 2888, election: 3888, jmx: 9000}
        lifecycle:
          running: [{type: tcp, port: client}]
      zk3:
        ship: ship3
        ports: {client: 2181, peer: 2888, election: 3888, jmx: 9000}
        lifecycle:
          running: [{type: tcp, port: client}]
```
