### ISSUE TITLE
Check for containers with the same name

### ISSUE THREAD

**Issue by fcoelho** [signalfuse/maestro-ng#32]
Say I have this yaml file:

```yaml
name: demo
ships:
  main: {ip: 172.17.42.1}
services:
  one:
    image: someimage
    instances:
      myinstance:
        ship: main
  two:
    image: otherimage
    instances:
      myinstance:
        ship: main
```
As can be seen, there are two instances with the name ``myinstance``. If I try to ``start`` this file, only one of the two instances is created. No error, no warning or anything. In this simple case it's easy to spot that you've started only one container instead of two, but on a more complex setup this could be easily overlooked.

Maestro should warn the user about this, possibly refusing to do anything before the error is fixed. On a similar note, if the first "name" key is ommited, only a ``KeyError: 'name'`` is thrown, which is also not very informative.

I have tested this only with containers on the same host, I haven't checked maestro's behavior when running in multiple hosts.
